- .gitignore
- README.md
- Testing/.gitignore
update README of @dzimmer and removal of Testing folder
> update README of @dzimmer and removal of Testing folder

- ThermofluidStream/Examples/ReverseHeatPump.mo
- ThermofluidStream/HeatExchangers/Internal/package.order
- ThermofluidStream/Sensors/Internal/Types.mo
- ThermofluidStream/Undirected/HeatExchangers/DiscretizedHEX.mo
- ThermofluidStream/Undirected/HeatExchangers/Internal/ConductionElementHEX_twoPhase.mo
- ThermofluidStream/Undirected/HeatExchangers/Internal/InitializationMethodsCondElementHEX.mo
- ThermofluidStream/Undirected/HeatExchangers/Internal/package.order
- Moved init methods from directed to undirected package
- Updated initialization in reverse heat pump
- corrected typo in sensor types
> Moved init methods and corrected typo in Sensors

- ThermofluidStream/Boundaries/DynamicPressureInflow.mo
- ThermofluidStream/Interfaces/SISOFlow.mo
- ThermofluidStream/Utilities/Types.mo
Hello, 
I found the following typos within SISOFlow.mo and Types.mo.
Please check!
Bests,
> Typo Correction

- ThermofluidStream/Interfaces/SISOFlow.mo
Fixed wrong comment in SISO flow, closes #52
> Fix wrong comment in SISO flow

- ThermofluidStream/Examples/Utilities/ReceiverUndirected.mo
- ThermofluidStream/Media/XRGMedia.mo
- ThermofluidStream/Media/myMedia/Interfaces.mo
- ThermofluidStream/Media/myMedia/R134a.mo
- ThermofluidStream/Topology/NonPhysical.mo
- ThermofluidStream/Undirected/Internal/regStep.mo
- ThermofluidStream/UserGuide/References/package.mo
- ThermofluidStream/UserGuide/package.mo
Changes according to conventions established in Modelica Standard Library.
> Fix html tags

- ThermofluidStream/Boundaries/DynamicPressureInflow.mo
- ThermofluidStream/Boundaries/DynamicPressureOutflow.mo
- ThermofluidStream/DropOfCommons.mo
- ThermofluidStream/Examples/ReverseHeatPump.mo
- ThermofluidStream/Examples/VenturiPump.mo
- ThermofluidStream/FlowControl/Internal/ControlValve/partialValveCharacteristics.mo
- ThermofluidStream/FlowControl/Internal/Curves/PartialCharacteristicZetaCurves.mo
- ThermofluidStream/FlowControl/Internal/Curves/SlideValveZetaCurve.mo
- ThermofluidStream/FlowControl/Internal/PartialValve.mo
- ThermofluidStream/FlowControl/MCV.mo
- ThermofluidStream/FlowControl/SpecificValveType.mo
- ThermofluidStream/HeatExchangers/CounterFlowNTU.mo
- ThermofluidStream/HeatExchangers/CrossFlowNTU.mo
- ThermofluidStream/HeatExchangers/Internal/calculateEfficency.mo
- ThermofluidStream/HeatExchangers/Tests/FlowRes.mo
- ThermofluidStream/Media/XRGMedia.mo
- ThermofluidStream/Media/myMedia/Water/WaterIF97_base.mo
- ThermofluidStream/Processes/ConductionElement.mo
- ThermofluidStream/Processes/Nozzle.mo
- ThermofluidStream/Processes/ThermalConvectionPipe.mo
- ThermofluidStream/Sensors/DifferenceSensorSelect.mo
- ThermofluidStream/Topology/NonPhysical.mo
- ThermofluidStream/Undirected/FlowControl/MCV.mo
- ThermofluidStream/Undirected/FlowControl/SpecificValveType.mo
- ThermofluidStream/Undirected/HeatExchangers/DiscretizedCrossFlowHEX.mo
- ThermofluidStream/Undirected/Processes/ConductionElement.mo
- ThermofluidStream/Utilities/Units.mo
- ThermofluidStream/Utilities/showRealValue.mo
This concerns description strings of 
- classes
- components
- parameters
(Detected by style check.)
> Fix missing or false description strings

- ThermofluidStream/Media/XRGMedia.mo
> Fix duplicated class definitions

- ThermofluidStream/Processes/Internal/TurboComponent/partial_dp_tau.mo
> Use types of nested package 'Medium' for inputs and outputs

- ThermofluidStream/HeatExchangers/Internal/DiscretizedHexIcon.mo
- ThermofluidStream/Processes/Internal/FlowResistance/laminarTurbulentPressureLossHaaland.mo
- ThermofluidStream/Sensors/Internal/Types.mo
- ThermofluidStream/Undirected/HeatExchangers/DiscretizedCounterFlowHEX.mo
- ThermofluidStream/Undirected/HeatExchangers/DiscretizedCrossFlowHEX.mo
According to MSL, see e.g. https://github.com/modelica/ModelicaStandardLibrary/pull/3723
> Delete byte order mark (BOM)

- ThermofluidStream/Media/myMedia/Water/IF97_Utilities.mo
Since they are neither input nor output.
See also corresponding commit in MSL: https://github.com/modelica/ModelicaStandardLibrary/commit/41a41cb396cf1cbbce483f993dc48efd76bed04a
> Make constants in functions protected

- ThermofluidStream/UserGuide/ReleaseNotes.mo
- ThermofluidStream/UserGuide/package.order
Following the repo tags, I marked Version 0.5.0 (2022-11-10) as the first official version of the library.
> Add release notes

- ThermofluidStream/UserGuide/ReleaseNotes.mo
Document changes done in https://github.com/DLR-SR/ThermofluidStream/pull/95
> Document changes (diagram and icon) on Inlet and Outlet

- ThermofluidStream/Media/myMedia/Interfaces.mo
- ThermofluidStream/Processes/Nozzle.mo
> Description strings start with "= true, if..." 

- ThermofluidStream/Boundaries/Sink.mo
- ThermofluidStream/Boundaries/Source.mo
- ThermofluidStream/Boundaries/TerminalSink.mo
- ThermofluidStream/HeatExchangers/DiscretizedCounterFlowHEX.mo
- ThermofluidStream/HeatExchangers/DiscretizedCounterFlowHEX_FR.mo
- ThermofluidStream/HeatExchangers/DiscretizedCrossFlowHEX.mo
- ThermofluidStream/HeatExchangers/DiscretizedCrossFlowHEX_FR.mo
- ThermofluidStream/HeatExchangers/Internal/DiscretizedHexIcon.mo
- ThermofluidStream/Sensors/DifferenceSensorSelect.mo
- ThermofluidStream/Sensors/DifferenceTwoPhaseSensorSensorSelect.mo
- ThermofluidStream/Undirected/Boundaries/BoundaryFore.mo
- ThermofluidStream/Undirected/Boundaries/BoundaryRear.mo
- ThermofluidStream/Undirected/Boundaries/TerminalFore.mo
- ThermofluidStream/Undirected/Boundaries/TerminalRear.mo
- ThermofluidStream/Undirected/FlowControl/BasicControlValve.mo
- ThermofluidStream/Undirected/FlowControl/CheckValve.mo
- ThermofluidStream/Undirected/FlowControl/MCV.mo
- ThermofluidStream/Undirected/FlowControl/SpecificValveType.mo
- ThermofluidStream/Undirected/FlowControl/TanValve.mo
- ThermofluidStream/Undirected/HeatExchangers/DiscretizedCounterFlowHEX.mo
- ThermofluidStream/Undirected/HeatExchangers/DiscretizedCrossFlowHEX.mo
- ThermofluidStream/Undirected/Topology/JunctionMN.mo
- Also updated consistency between the different models.
- Improved consistency of connection lines in various component icons.
> Added A and B to Discretized HEX, updated arrows for consistent directions

- ThermofluidStream/Processes/Internal/TurboComponent/dp_tau_centrifugal.mo
- ThermofluidStream/Processes/Internal/TurboComponent/dp_tau_nominal_flow.mo
- Changed from the inconsistent 1/s to rad/s
> Corrected display unit of nominal flow pump omega

- ThermofluidStream/Topology/JunctionN.mo
- ThermofluidStream/Topology/JunctionNM.mo
- ThermofluidStream/Topology/SplitterN.mo
So the icon looks similar like Modelica.Blocks.Routing.Replicator. (I know, the element's behavior is indeed different. ;-) )
> Icon: add more lines to an array connector

- ThermofluidStream/FlowControl/Internal/PartialValve.mo
- ThermofluidStream/Undirected/FlowControl/Internal/PartialValve.mo
Reverts DLR-SR/ThermofluidStream#111
> Revert "Added regSquare to partial valve models for improved robustness "

- .github/labeler.yml
- .github/workflows/label.yml
This automation adds 'label' on Pull Request, if only files of one package are changed
> Git automation: add labeler

- .CI/check_deprecated_line_color.py
This adaption bases on MSL changes in https://github.com/modelica/ModelicaStandardLibrary/pull/4183
> Improve check pattern for deprecated Text.lineColor annotation

- ThermofluidStream/HeatExchangers/Tests/CrossFlowNTU_zeroMassFlow.mo
Fixes wrong medium definition in `flowResistance` on path A.
> Fix wrong medium definition

- .gitignore
> Enable png-files

- CONTRIBUTING.md
The contributing.md was mostly taken from the MSL contributors guideline.
> Guideline how to contribute to library
